language: go

go:
  - "1.10"

before_script:
  - "make golang-dep"
  
script: 
  - "./.travis/buildViaTravis.sh"

before_deploy:
  - cat VERSION | xargs git tag

deploy:
  provider: releases
  api_key: $GITHUB_RELEASE_TOKEN
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    brach: master
    tag: true