language: go

go:
  - "1.10"

before_script:
  - go get github.com/Clever/gitsem
  - make golang-dep
  
script: 
  - ./.travis/buildViaTravis.sh

before_deploy:
  gitsem minor
  # - cat VERSION | xargs git tag

deploy:
  provider: releases
  api_key: $GITHUB_RELEASE_TOKEN
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    brach: master
    tag: true