language: go

go:
  - "1.10"

before_script:
  - go get github.com/eloo/gitsem
  - make golang-dep
  - gitsem minor -skip-repo-check=true -m "[ci skip]"
  
script: 
  - ./.travis/buildViaTravis.sh

before_deploy:
  # gitsem -skip-repo-check=true minor
  # - cat VERSION | xargs git tag

deploy:
  provider: releases
  api_key: $GITHUB_RELEASE_TOKEN
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    brach: master
    # tag: true